// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;


class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
   
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
    
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApGwoAvDCXD7OHCk-JvgOakGr2dVJoW5o',
    appId: '1:70964143073:android:95a58dca5fd223540d28a0',
    messagingSenderId: '70964143073',
    projectId: 'pokemon-card-collection-f9e21',
    storageBucket: 'pokemon-card-collection-f9e21.firebasestorage.app',
  );
}